### ISSUE TITLE
Investigate Duplicate Logging of Sequence Conflicts

### ISSUE THREAD

**Issue by sklose** [walmartlabs/cookie-cutter#42]
We only expect to see a warning for sequence number conflicts and not the generic sink error in addition to that. Also this could be related to #41, if the sequence conflict is actually not retried then any subsequent message would enter an infinite loop.

This behavior was observed on 1.2-beta

```
{"log":{"time":"2020-01-22T21:29:58.773Z","level":"WARN","ctx":"XXX","fields":{"msg":["sequence number conflict, retrying"],"key":["5afff00439bb52762d53f00d17a7afe2"],"newSn":[74],"expectedSn":[74],"actualSn":[75]}},"stream":"stdout","time":"2020-01-22T21:29:58.773822339Z"}
--
{"log":{"time":"2020-01-22T21:29:58.772Z","level":"EROR","ctx":"XXX","fields":{"msg":["failed to process output in sink"],"err":["failed to store message due to sequence number conflict: key: 5afff00439bb52762d53f00d17a7afe2, newSn: 74, expectedSn: 74 actualSn: 75"],"stack":["Error: failed to store message due to sequence number conflict: key: 5afff00439bb52762d53f00d17a7afe2, newSn: 74, expectedSn: 74 actualSn: 75
    at CompositeOutputSink.\u003canonymous\u003e (/usr/src/node_modules/@walmartlabs/cookie-cutter-core/dist/internal/CompositeOutputSink.js:45:26)
    at Generator.next (\u003canonymous\u003e)
    at fulfilled (/usr/src/node_modules/@walmartlabs/cookie-cutter-core/dist/internal/CompositeOutputSink.js:11:58)
    at runMicrotasks (\u003canonymous\u003e)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)"]}},"stream":"stdout","time":"2020-01-22T21:29:58.773213315Z"}
```

**Comment by plameniv** [comment]
Addressed by linked PR
