### ISSUE TITLE
Unable to retrieve watermarks

### ISSUE THREAD

**Issue by sklose** [walmartlabs/cookie-cutter#5]
The background task that publishes Kafka metrics seems to be able to get into a bad state.

```
TypeError: Cannot destructure property `partitions` of 'undefined' or 'null'.
    at /usr/src/node_modules/kafkajs/src/admin/index.js:209:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by plameniv** [comment]
This issue opened with Kafkajs seems related but hasn't had any updates since August.

https://github.com/tulios/kafkajs/issues/461

**Comment by plameniv** [comment]
No one seems to be working on this on the Kafkajs side. @talam do you happen to have a reproducer for the issue?
